#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Iterable

from _claim_model import build_claim_register
from _stage_contracts import build_claim_map_from_stage_json, normalize_source_record
from _workflow_lib import write_json


# These patterns intentionally stay permissive because the input is often
# semi-structured notes rather than clean markdown generated by one tool.
CITATION_BLOCK_PATTERN = re.compile(r"\[([^\[\]]+)\]")
LIST_PREFIX_PATTERN = re.compile(r"^\s*(?:[-*+]\s+|\d+[.)]\s+)")
MARKDOWN_HEADING_PATTERN = re.compile(r"^\s{0,3}#{1,6}\s+(.*)$")
PLAIN_HEADING_PATTERN = re.compile(
    r"^\s*(facts?|inferences?|analysis|claims?|findings|evaluations?|decisions?|"
    r"open questions?|evidence gaps?|report structure)\s*:?\s*$",
    re.IGNORECASE,
)
CONFIDENCE_PATTERN = re.compile(
    r"(?:^|[\s;,(])confidence\s*[:=-]?\s*(low|medium(?:\s*-\s*high)?|high)\b",
    re.IGNORECASE,
)
SENTENCE_SPLIT_PATTERN = re.compile(r"(?<!\bvs\.)(?<=[.!?])\s+(?!(?:Confidence)\b)(?=[A-Z0-9\"'`])")
PROVENANCE_TOKEN_PATTERN = re.compile(
    r"^(?:PASS|CRIT|JUDGE|INTAKE|WORK[_-]?ORDER|RUN|STAGE|SYNTHESIS|ARTIFACT)"
    r"(?:[-_][A-Z0-9]+)*$",
    re.IGNORECASE,
)
EVIDENCE_TOKEN_PATTERN = re.compile(
    r"^(?:SRC|DOC)-[A-Z0-9._-]+$|^S[0-9]{1,6}$|^https?://\S+$|^file://\S+$|^app://\S+$|^(?:~?/|/|\./|\.\./)\S+$",
    re.IGNORECASE,
)
PATH_ONLY_PATTERN = re.compile(
    r"^`?(?:~?/|/|\./|\.\./)[^`]+`?$|^`?[^`\s]+(?:/[^`\s]+)+`?$"
)
REPORT_STRUCTURE_PATTERN = re.compile(
    r"^(?:recommended\s+section\s+structure|section\s+structure|outline)\s*:?\s*$",
    re.IGNORECASE,
)
HEADING_LABEL_PATTERN = re.compile(
    r"^(?:evidence gaps?|open questions?|findings|report structure|analysis|claims?)\s*:?\s*$",
    re.IGNORECASE,
)


def normalize_whitespace(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def classify_marker(marker: str, source_index: dict[str, dict[str, str]] | None = None) -> tuple[str, str]:
    normalized = normalize_whitespace(marker)
    if source_index and normalized in source_index:
        source_class = source_index[normalized].get("source_class", "")
        if source_class == "workflow_provenance":
            return "provenance", normalized
        return "evidence", normalized
    if EVIDENCE_TOKEN_PATTERN.match(normalized):
        return "evidence", normalized
    if PROVENANCE_TOKEN_PATTERN.match(normalized):
        return "provenance", normalized.upper()
    return "unclassified", normalized


def extract_citations(text: str, source_index: dict[str, dict[str, str]] | None = None) -> tuple[list[str], list[str], list[str]]:
    provenance: list[str] = []
    evidence_sources: list[str] = []
    unclassified_markers: list[str] = []
    for block in CITATION_BLOCK_PATTERN.findall(text):
        for part in block.split(","):
            candidate = normalize_whitespace(part)
            if not candidate:
                continue
            marker_type, normalized = classify_marker(candidate, source_index)
            if marker_type == "evidence":
                evidence_sources.append(normalized)
            elif marker_type == "provenance":
                provenance.append(normalized)
            else:
                unclassified_markers.append(normalized)
    return provenance, evidence_sources, unclassified_markers


def strip_citations(text: str) -> str:
    return normalize_whitespace(CITATION_BLOCK_PATTERN.sub("", text))


def extract_confidence(text: str) -> tuple[str | None, str]:
    match = CONFIDENCE_PATTERN.search(text)
    if not match:
        return None, text
    confidence = re.sub(r"\s*-\s*", "-", match.group(1).lower())
    if confidence == "medium-high":
        confidence = "high"
    cleaned = normalize_whitespace(CONFIDENCE_PATTERN.sub(" ", text))
    return confidence, cleaned


def canonical_heading(text: str) -> str | None:
    markdown_heading = MARKDOWN_HEADING_PATTERN.match(text)
    if markdown_heading:
        return normalize_whitespace(markdown_heading.group(1))

    plain_heading = PLAIN_HEADING_PATTERN.match(text)
    if plain_heading:
        return normalize_whitespace(plain_heading.group(1))

    return None


def claim_type_for_heading(heading: str | None) -> str:
    lowered = (heading or "").lower()
    if "unresolved disagreement" in lowered or "confidence assessment" in lowered:
        return "evaluation"
    if "evidence gap" in lowered:
        return "evidence_gap"
    if "open question" in lowered:
        return "open_question"
    if "rationale" in lowered or "traceability" in lowered:
        return "evaluation"
    if "evaluation" in lowered or "finding" in lowered or "analysis" in lowered:
        return "evaluation"
    if "decision" in lowered:
        return "decision"
    if "report structure" in lowered:
        return "report_structure"
    if "artifact" in lowered:
        return "artifact_reference"
    if any(token in lowered for token in ("inference", "analysis", "interpret")):
        return "inference"
    return "fact"


def is_probable_claim_line(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    if stripped.startswith(">") or stripped.startswith("```"):
        return False
    if canonical_heading(stripped):
        return False
    if LIST_PREFIX_PATTERN.match(stripped):
        return True
    return bool(re.search(r"[.!?]|\[[^\]]+\]|confidence", stripped, re.IGNORECASE))


def is_non_claim_text(text: str) -> bool:
    stripped = normalize_whitespace(text).strip("`").strip()
    if not stripped:
        return True
    if PATH_ONLY_PATTERN.match(stripped):
        return True
    if REPORT_STRUCTURE_PATTERN.match(stripped):
        return True
    if HEADING_LABEL_PATTERN.match(stripped):
        return True
    confidence, cleaned = extract_confidence(stripped)
    if confidence and not strip_citations(cleaned).strip(" :;-"):
        return True
    if stripped.endswith(":") and len(stripped.split()) <= 5:
        return True
    return False


def split_into_atomic_units(text: str) -> list[str]:
    # First split on sentence boundaries, then split again when a citation block
    # is followed by a new sentence. This is not perfect, but it is better than
    # treating whole paragraphs as claims.
    parts: list[str] = []
    for chunk in SENTENCE_SPLIT_PATTERN.split(text):
        chunk = normalize_whitespace(chunk)
        if not chunk:
            continue
        subparts = re.split(r"(?<=\])\s+(?!(?:Confidence)\b)(?=[A-Z0-9\"'`])", chunk)
        for subpart in subparts:
            cleaned = normalize_whitespace(subpart)
            if cleaned:
                parts.append(cleaned)
    return parts if parts else [normalize_whitespace(text)]


def infer_claim_type(text: str, heading: str | None) -> str:
    if heading:
        heading_type = claim_type_for_heading(heading)
        if heading_type != "fact":
            return heading_type
    lowered = text.lower()
    if text.endswith("?"):
        return "open_question"
    if any(marker in lowered for marker in ("evidence gap", "no external source", "no source confirms")):
        return "evidence_gap"
    if any(marker in lowered for marker in ("accepted", "rejected", "adequate", "insufficient", "stronger", "weaker")):
        return "evaluation"
    if any(marker in lowered for marker in ("decided", "decision", "will use", "selected")):
        return "decision"
    if REPORT_STRUCTURE_PATTERN.match(lowered) or "section structure" in lowered:
        return "report_structure"
    inference_markers = ("likely", "suggests", "implies", "may ", "might ", "could ", "appears to")
    if any(marker in lowered for marker in inference_markers):
        return "inference"
    return "fact"


def iter_candidate_claims(markdown: str) -> Iterable[tuple[int, str | None, str]]:
    active_heading: str | None = None
    for line_number, raw_line in enumerate(markdown.splitlines(), start=1):
        stripped = raw_line.strip()
        if not stripped:
            continue

        heading = canonical_heading(stripped)
        if heading is not None:
            active_heading = heading
            continue

        if not is_probable_claim_line(raw_line):
            continue

        cleaned_line = LIST_PREFIX_PATTERN.sub("", stripped)
        for atomic_unit in split_into_atomic_units(cleaned_line):
            if atomic_unit:
                yield line_number, active_heading, atomic_unit


def build_claim_record(
    index: int,
    line_number: int,
    heading: str | None,
    raw_text: str,
    source_index: dict[str, dict[str, str]] | None = None,
) -> dict[str, object]:
    provenance, evidence_sources, unclassified_markers = extract_citations(raw_text, source_index)
    confidence, without_confidence = extract_confidence(raw_text)
    text = strip_citations(without_confidence)
    text = text.rstrip(" ;,")

    record: dict[str, object] = {
        "id": f"C{index:03d}",
        "text": text,
        "type": infer_claim_type(text, heading),
        "provenance": provenance,
        "evidence_sources": evidence_sources,
        "unclassified_markers": unclassified_markers,
        "line": line_number,
    }
    if heading:
        record["section"] = heading
    if confidence is not None:
        record["confidence"] = confidence
    return record


def extract_claims(markdown: str, source_index: dict[str, dict[str, str]] | None = None) -> list[dict[str, object]]:
    claims: list[dict[str, object]] = []
    seen_keys: set[tuple[str, int]] = set()

    for line_number, heading, raw_text in iter_candidate_claims(markdown):
        if not raw_text:
            continue
        preview = strip_citations(extract_confidence(raw_text)[1])
        if is_non_claim_text(preview):
            continue
        key = (preview.lower(), line_number)
        if not preview or key in seen_keys:
            continue
        seen_keys.add(key)
        claims.append(build_claim_record(len(claims) + 1, line_number, heading, raw_text, source_index))

    return claims


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract atomic claims from a markdown document into a JSON claim register.",
        epilog=(
            "Example: python3 scripts/extract_claims.py --input report.md --output claims.json --strict"
        ),
    )
    parser.add_argument("--input", required=True, help="Path to the markdown input file.")
    parser.add_argument("--output", required=True, help="Path to the JSON claim register to write.")
    parser.add_argument("--source-registry", help="Optional path to a source registry for semantic citation classification during markdown extraction.")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Return a non-zero exit code when any extracted fact or inference claim lacks external evidence sources.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_path = Path(args.input).expanduser()
    output_path = Path(args.output).expanduser()
    source_registry_path = Path(args.source_registry).expanduser() if args.source_registry else None

    if not input_path.exists():
        print(f"Input file not found: {input_path}", file=sys.stderr)
        return 1
    if not input_path.is_file():
        print(f"Input path is not a file: {input_path}", file=sys.stderr)
        return 1

    try:
        source_index: dict[str, dict[str, str]] | None = None
        if source_registry_path is not None and source_registry_path.is_file():
            registry_payload = json.loads(source_registry_path.read_text(encoding="utf-8"))
            source_index = {}
            for source in registry_payload.get("sources", []):
                if not isinstance(source, dict):
                    continue
                normalized_source = normalize_source_record(source)
                source_id = normalized_source.get("id")
                if isinstance(source_id, str) and source_id.strip():
                    source_index[source_id] = {
                        key: str(value)
                        for key, value in normalized_source.items()
                        if isinstance(value, str)
                    }
        if input_path.suffix.lower() == ".json":
            structured_payload = json.loads(input_path.read_text(encoding="utf-8"))
            stage_id = structured_payload.get("stage")
            if isinstance(stage_id, str) and stage_id in {"research-a", "research-b", "critique-a-on-b", "critique-b-on-a", "judge"}:
                payload = build_claim_map_from_stage_json(stage_id, structured_payload)
            else:
                raise ValueError("JSON input is not a recognized structured stage artifact.")
        else:
            markdown = input_path.read_text(encoding="utf-8")
            claims = extract_claims(markdown, source_index)
            payload = build_claim_register(claims)
        write_json(output_path, payload)
    except UnicodeDecodeError:
        print(f"Could not decode input file as UTF-8: {input_path}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"Failed to process files: {exc}", file=sys.stderr)
        return 1
    except Exception as exc:
        # Defensive catch: the script is part of an orchestration pipeline and
        # should fail with a clear message rather than a traceback by default.
        print(f"Claim extraction failed: {exc}", file=sys.stderr)
        return 1

    uncited_facts = payload["summary"]["uncited_fact_ids"]
    uncited_inferences = payload["summary"]["uncited_inference_ids"]
    provenance_only_facts = payload["summary"]["provenance_only_fact_ids"]
    if args.strict and (uncited_facts or uncited_inferences):
        parts = []
        if uncited_facts:
            parts.append("Uncited fact claims detected: " + ", ".join(uncited_facts))
        if uncited_inferences:
            parts.append("Uncited inference claims detected: " + ", ".join(uncited_inferences))
        if provenance_only_facts:
            parts.append("Provenance-only fact claims detected: " + ", ".join(provenance_only_facts))
        print(" ".join(parts), file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
